version: "3.3"

services:
  web:
    build:
      dockerfile: Dockerfile.web
    #    command: java -jar /build/target/app.jar
    container_name: springapp
    volumes:
      - "./src:/build/src"
#      - "./target:/build/target:cached"
    ports:
      - 8080:8080
