FROM maven:3.8.7-openjdk-18 as builder

RUN mkdir -p /build
RUN mkdir -p /build/logs
RUN mkdir -p /build/app

WORKDIR /build
COPY pom.xml /build
COPY src /build/src/

RUN mvn package
#RUN mvn clean install spring-boot:repackage
RUN ls
#ARG JAR_FILE=/target/*.jar
#COPY ${JAR_FILE} app.jar

#WORKDIR /app
ENTRYPOINT ["java", "-jar", "/build/target/Bybit-0.0.1-SNAPSHOT.jar"]
